version: "3.8"
services:
  app:
    container_name: app
    image: node-typescript
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - API_HOST=app
      - PORT=80
    ports:
      - "3000:80"
    