services:
  recopiladora:
    container_name: app
    image: node-typescript
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - API_HOST=app
      - PORT=80
    ports:
      - "3001:80"
    volumes:
      - ./src:/app/src
      - ./__tests__:/app/__tests__